build:
	make -C self build
	make -C TP build
	make -C GNOME build
	make -C KDE build
	make -C MATE build
	make -C R build
	make -C Fedora build
	make -C misc build
	make -C etoys build
	make -C noinstall build
	make -C libreoffice build

install:
	make -C self install
	make -C TP install
	make -C GNOME install
	make -C KDE install
	make -C MATE install
	make -C R install
	make -C Fedora install
	make -C misc install
	make -C etoys install
