build:
	make -C sugar build
	make -C XFCE build
	make -C TP build
	make -C GNOME build
	make -C KDE build
	make -C MATE build
	make -C R build
	make -C Fedora build
	make -C selfdir build
	make -C sysdir build
	make -C etoys build
	make -C libreoffice build
	make -C noinstall build

install:
	make -C sugar install
	make -C XFCE install
	make -C TP install
	make -C GNOME install
	make -C KDE install
	make -C MATE install
	make -C R install
	make -C Fedora install
	make -C selfdir install
	make -C sysdir install
	make -C etoys install
	make -C libreoffice install