<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
    <name>KBookmarkDialog</name>
    <message>
        <source>Add</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Name:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Add Bookmark</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Add Bookmarks</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>New Folder</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Update</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bookmarks</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Comment:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&amp;New Folder...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bookmark Properties</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Location:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Create New Bookmark Folder in %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>New folder:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Select Folder</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Create New Bookmark Folder</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KNSBookmarkImporterImpl</name>
    <message>
        <source>HTML Files (*.html)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Could not find %1. Netscape is probably not installed. Aborting the export.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bookmarks</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>&lt;!-- This file was generated by Konqueror --&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Netscape not found</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>*.html|HTML Files (*.html)</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KonqBookmarkContextMenu</name>
    <message>
        <source>Hide in toolbar</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Open in New Tab</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Show in toolbar</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Open in New Window</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KBookmarkContextMenu</name>
    <message>
        <source>Are you sure you wish to remove the bookmark folder
&quot;%1&quot;?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Add Bookmark Here</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Copy Link Address</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bookmark Folder Deletion</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Properties</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Are you sure you wish to remove the bookmark
&quot;%1&quot;?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Delete Bookmark</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Cannot add bookmark with empty URL.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bookmark Deletion</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Open Folder in Tabs</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Delete Folder</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Open Folder in Bookmark Editor</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KBookmarkMenu</name>
    <message>
        <source>Add a folder of bookmarks for all open tabs.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Create a new bookmark folder in this menu</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Edit your bookmark collection in a separate window</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Open Folder in Tabs</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Open all bookmarks in this folder as a new tab.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>New Bookmark Folder...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Bookmark Tabs as Folder...</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KBookmarkManager</name>
    <message>
        <source>Unable to save bookmarks in %1. Reported error was: %2. This error message will only be shown once. The cause of the error needs to be fixed as quickly as possible, which is most likely a full hard drive.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Cannot launch keditbookmarks.

Most likely you do not have keditbookmarks currently installed</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KBookmark</name>
    <message>
        <source>--- separator ---</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KOperaBookmarkImporterImpl</name>
    <message>
        <source>*.adr|Opera Bookmark Files (*.adr)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Opera Bookmark Files (*.adr)</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
